/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        // Legacy colors (to be replaced in Tiers 2 & 3)
        bg: "#0a0a0f",
        border: "#1e1e2e",
        accent: "#7c3aed",
        "accent-hover": "#6d28d9",
        "accent-light": "#a855f7",
        text: "#f4f4f5",
        muted: "#71717a",
        "score-audio": "#f59e0b",
        "score-scene": "#10b981",
        "score-lexical": "#7c3aed",
        success: "#22c55e",
        warning: "#f59e0b",
        
        // Stitch Design System Colors
        "inverse-primary": "#494bd6",
        "on-error-container": "#ffdad6",
        "inverse-on-surface": "#303038",
        "surface-variant": "#34343d",
        "surface-container-high": "#292932",
        "on-tertiary-fixed": "#301400",
        "on-tertiary-container": "#452000",
        "primary": "#c0c1ff",
        "on-error": "#690005",
        "outline-variant": "#464554",
        "secondary": "#4cd7f6",
        "on-background": "#e4e1ed",
        "outline": "#908fa0",
        "error-container": "#93000a",
        "on-secondary-container": "#00424e",
        "primary-fixed-dim": "#c0c1ff",
        "surface-bright": "#393841",
        "secondary-fixed-dim": "#4cd7f6",
        "error": "#ffb4ab",
        "on-secondary-fixed": "#001f26",
        "tertiary-container": "#d97721",
        "on-primary-fixed": "#07006c",
        "on-tertiary": "#4f2500",
        "primary-container": "#8083ff",
        "on-primary": "#1000a9",
        "inverse-surface": "#e4e1ed",
        "surface-container-low": "#1b1b23",
        "tertiary-fixed-dim": "#ffb783",
        "secondary-fixed": "#acedff",
        "on-tertiary-fixed-variant": "#703700",
        "surface-container-lowest": "#0d0d15",
        "primary-fixed": "#e1e0ff",
        "tertiary-fixed": "#ffdcc5",
        "on-primary-fixed-variant": "#2f2ebe",
        "on-surface": "#e4e1ed",
        "surface-tint": "#c0c1ff",
        "surface-dim": "#13131b",
        "on-primary-container": "#0d0096",
        "on-secondary": "#003640",
        "surface-container-highest": "#34343d",
        "secondary-container": "#03b5d3",
        "surface-container": "#1f1f27",
        "tertiary": "#ffb783",
        "surface": "#13131b",
        "on-surface-variant": "#c7c4d7",
        "background": "#13131b",
        "on-secondary-fixed-variant": "#004e5c"
      },
      spacing: {
        "unit": "4px",
        "stack-sm": "8px",
        "gutter": "16px",
        "stack-md": "16px",
        "container-margin": "24px",
        "stack-lg": "32px"
      },
      fontFamily: {
        "body-sm": ["Inter"],
        "mono-sm": ["Geist"],
        "body-md": ["Inter"],
        "headline-sm": ["Inter"],
        "body-lg": ["Inter"],
        "headline-lg": ["Inter"],
        "headline-md": ["Inter"],
        "label-caps": ["Geist"],
        "sans": ["Inter", "system-ui", "sans-serif"],
        "mono": ["Geist", "monospace"],
      },
      fontSize: {
        "body-sm": ["14px", { "lineHeight": "1.5", "fontWeight": "400" }],
        "mono-sm": ["13px", { "lineHeight": "1.4", "fontWeight": "400" }],
        "body-md": ["16px", { "lineHeight": "1.5", "fontWeight": "400" }],
        "headline-sm": ["24px", { "lineHeight": "1.3", "fontWeight": "600" }],
        "body-lg": ["18px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "headline-lg": ["48px", { "lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "headline-md": ["32px", { "lineHeight": "1.2", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "label-caps": ["12px", { "lineHeight": "1.0", "letterSpacing": "0.05em", "fontWeight": "600" }]
      },
      animation: {
        "pulse-slow": "pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite",
        "fade-in": "fadeIn 0.3s ease-out",
        "slide-up": "slideUp 0.4s ease-out",
      },
      keyframes: {
        fadeIn: { "0%": { opacity: 0 }, "100%": { opacity: 1 } },
        slideUp: {
          "0%": { opacity: 0, transform: "translateY(16px)" },
          "100%": { opacity: 1, transform: "translateY(0)" },
        },
      },
    },
  },
  plugins: [],
};
